#!/usr/bin/env python3
"""
Proxy Chain Manager
Manages SOCKS5/HTTP proxies, tests connectivity, and generates proxychains configs.
"""

import argparse
import json
import socket
import time
import urllib.request
import urllib.error
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor, as_completed

PROXY_DB = Path("~/.opsec/proxies.json").expanduser()
TEST_URL = "http://httpbin.org/ip"
TIMEOUT = 8


# ─────────────────────────── storage ────────────────────────────────

def load_proxies() -> list[dict]:
    if PROXY_DB.exists():
        return json.loads(PROXY_DB.read_text())
    return []


def save_proxies(proxies: list[dict]):
    PROXY_DB.parent.mkdir(parents=True, exist_ok=True)
    PROXY_DB.write_text(json.dumps(proxies, indent=2))


# ─────────────────────────── testing ────────────────────────────────

def test_socks5_proxy(host: str, port: int) -> tuple[bool, float]:
    """Test a SOCKS5 proxy by connecting and measuring latency."""
    try:
        start = time.time()
        sock = socket.create_connection((host, port), timeout=TIMEOUT)
        # SOCKS5 handshake
        sock.sendall(b"\x05\x01\x00")
        response = sock.recv(2)
        elapsed = time.time() - start
        sock.close()
        if response[:1] == b"\x05":
            return True, round(elapsed * 1000, 1)
        return False, 0.0
    except Exception:
        return False, 0.0


def test_http_proxy(host: str, port: int) -> tuple[bool, float]:
    """Test an HTTP proxy by making a CONNECT request."""
    try:
        start = time.time()
        proxy_handler = urllib.request.ProxyHandler({
            "http": f"http://{host}:{port}",
            "https": f"http://{host}:{port}",
        })
        opener = urllib.request.build_opener(proxy_handler)
        req = urllib.request.Request(TEST_URL)
        with opener.open(req, timeout=TIMEOUT) as resp:
            resp.read()
        elapsed = time.time() - start
        return True, round(elapsed * 1000, 1)
    except Exception:
        return False, 0.0


def test_proxy(proxy: dict) -> dict:
    """Test a proxy entry and return updated entry with status/latency."""
    proto = proxy.get("type", "socks5").lower()
    host = proxy["host"]
    port = proxy["port"]
    if proto in ("socks5", "socks4"):
        ok, ms = test_socks5_proxy(host, port)
    else:
        ok, ms = test_http_proxy(host, port)
    return {**proxy, "alive": ok, "latency_ms": ms if ok else None}


# ─────────────────────────── config generation ──────────────────────

def generate_proxychains_config(proxies: list[dict], chain_type: str = "strict") -> str:
    alive = [p for p in proxies if p.get("alive", True)]
    if not alive:
        alive = proxies  # fallback — include all

    lines = [
        "# Generated by OPSEC Proxy Chain Manager",
        f"# Chain type: {chain_type}",
        "",
        f"{chain_type}_chain",
        "proxy_dns",
        "remote_dns_subnet 224",
        "tcp_read_time_out 15000",
        "tcp_connect_time_out 8000",
        "",
        "[ProxyList]",
    ]
    for p in alive:
        proto = p.get("type", "socks5").lower()
        auth = ""
        if p.get("user") and p.get("password"):
            auth = f" {p['user']} {p['password']}"
        lines.append(f"{proto} {p['host']} {p['port']}{auth}")
    return "\n".join(lines)


def generate_burpsuite_upstream(proxies: list[dict]) -> str:
    alive = [p for p in proxies if p.get("alive", True)] or proxies
    if not alive:
        return ""
    p = alive[0]
    return (
        f"# BurpSuite upstream proxy settings\n"
        f"Proxy host: {p['host']}\n"
        f"Proxy port: {p['port']}\n"
        f"Type: {p.get('type','SOCKS5').upper()}\n"
    )


# ─────────────────────────── CLI commands ───────────────────────────

def cmd_add(args):
    proxies = load_proxies()
    entry = {
        "host": args.host,
        "port": args.port,
        "type": args.type,
        "user": args.user or "",
        "password": args.password or "",
        "label": args.label or f"{args.host}:{args.port}",
        "alive": None,
        "latency_ms": None,
    }
    proxies.append(entry)
    save_proxies(proxies)
    print(f"[+] Added proxy: {entry['type']} {entry['host']}:{entry['port']}")


def cmd_list(args):
    proxies = load_proxies()
    if not proxies:
        print("No proxies stored. Use 'add' to add some.")
        return
    print(f"{'#':<4} {'Type':<8} {'Host':<30} {'Port':<6} {'Status':<8} {'ms':<8} {'Label'}")
    print("-" * 80)
    for i, p in enumerate(proxies):
        status = "✓ alive" if p.get("alive") else ("✗ dead" if p.get("alive") is False else "?")
        ms = str(p.get("latency_ms") or "-")
        print(f"{i:<4} {p.get('type','socks5'):<8} {p['host']:<30} {p['port']:<6} {status:<8} {ms:<8} {p.get('label','')}")


def cmd_test(args):
    proxies = load_proxies()
    if not proxies:
        print("No proxies to test.")
        return
    print(f"[*] Testing {len(proxies)} proxies with {args.threads} threads …")
    with ThreadPoolExecutor(max_workers=args.threads) as ex:
        futures = {ex.submit(test_proxy, p): i for i, p in enumerate(proxies)}
        for fut in as_completed(futures):
            idx = futures[fut]
            result = fut.result()
            proxies[idx] = result
            status = f"ALIVE ({result['latency_ms']} ms)" if result["alive"] else "DEAD"
            print(f"  [{status}] {result['host']}:{result['port']}")
    save_proxies(proxies)
    alive = sum(1 for p in proxies if p.get("alive"))
    print(f"\n[+] Results: {alive}/{len(proxies)} alive")


def cmd_export(args):
    proxies = load_proxies()
    if args.format == "proxychains":
        cfg = generate_proxychains_config(proxies, chain_type=args.chain_type)
        out = Path(args.output)
        out.write_text(cfg)
        print(f"[+] proxychains config → {out}")
    elif args.format == "burp":
        cfg = generate_burpsuite_upstream(proxies)
        out = Path(args.output)
        out.write_text(cfg)
        print(f"[+] BurpSuite config   → {out}")
    elif args.format == "json":
        out = Path(args.output)
        out.write_text(json.dumps(proxies, indent=2))
        print(f"[+] JSON export        → {out}")


def cmd_remove(args):
    proxies = load_proxies()
    if args.index < 0 or args.index >= len(proxies):
        print(f"[!] Invalid index {args.index}")
        return
    removed = proxies.pop(args.index)
    save_proxies(proxies)
    print(f"[-] Removed proxy: {removed['host']}:{removed['port']}")


def main():
    parser = argparse.ArgumentParser(
        description="OPSEC Proxy Chain Manager",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python proxy_chain.py add --host 127.0.0.1 --port 9050 --type socks5 --label "Tor"
  python proxy_chain.py add --host proxy.example.com --port 8080 --type http
  python proxy_chain.py test --threads 20
  python proxy_chain.py list
  python proxy_chain.py export --format proxychains --output /etc/proxychains4.conf
  python proxy_chain.py export --format json --output proxies.json
        """,
    )
    sub = parser.add_subparsers(dest="command")

    # add
    p_add = sub.add_parser("add", help="Add a proxy")
    p_add.add_argument("--host", required=True)
    p_add.add_argument("--port", required=True, type=int)
    p_add.add_argument("--type", default="socks5", choices=["socks5", "socks4", "http"])
    p_add.add_argument("--user", default="")
    p_add.add_argument("--password", default="")
    p_add.add_argument("--label", default="")

    # list
    sub.add_parser("list", help="List all proxies")

    # test
    p_test = sub.add_parser("test", help="Test proxy connectivity")
    p_test.add_argument("--threads", type=int, default=10)

    # export
    p_exp = sub.add_parser("export", help="Export proxy config")
    p_exp.add_argument("--format", choices=["proxychains", "burp", "json"], default="proxychains")
    p_exp.add_argument("--chain-type", choices=["strict", "dynamic", "random"], default="dynamic")
    p_exp.add_argument("--output", default="proxychains.conf")

    # remove
    p_rm = sub.add_parser("remove", help="Remove proxy by index")
    p_rm.add_argument("index", type=int)

    args = parser.parse_args()
    dispatch = {
        "add": cmd_add,
        "list": cmd_list,
        "test": cmd_test,
        "export": cmd_export,
        "remove": cmd_remove,
    }
    if args.command in dispatch:
        dispatch[args.command](args)
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
