#!/usr/bin/env python3
"""
Tor Integration Helper
Generates torrc configs, tests Tor connectivity, and manages circuits.
"""

import argparse
import os
import socket
import time
import urllib.request
from pathlib import Path

TOR_SOCKS_PORT = 9050
TOR_CONTROL_PORT = 9051
TOR_TEST_URL = "https://check.torproject.org/api/ip"


# ─────────────────────────── torrc generation ───────────────────────

TORRC_TEMPLATE = """\
# Generated by OPSEC Tor Setup Helper
# Place this file at /etc/tor/torrc or ~/.torrc

SocksPort {socks_port}
ControlPort {control_port}
HashedControlPassword {hashed_pw}

# Logging
Log notice file /var/log/tor/notices.log

# Data directory
DataDirectory /var/lib/tor

# Circuit settings
MaxCircuitDirtiness 600
NewCircuitPeriod 30
CircuitBuildTimeout 60

# DNS through Tor
DNSPort 5353
AutomapHostsOnResolve 1

# Exit policy (relay config — comment out to run as client only)
ExitPolicy reject *:*

# Hidden service example (uncomment to enable)
# HiddenServiceDir /var/lib/tor/hidden_service/
# HiddenServicePort 80 127.0.0.1:8080

# Bridge / obfuscation (uncomment and fill in for censored networks)
# UseBridges 1
# Bridge obfs4 <IP>:<PORT> <FINGERPRINT> cert=<CERT> iat-mode=0
# ClientTransportPlugin obfs4 exec /usr/bin/obfs4proxy
"""

TORRC_TRANSPARENT = """\
# Transparent proxy (route ALL traffic through Tor)
# Use with iptables rules below

TransPort 9040
DNSPort 5353
AutomapHostsOnResolve 1
AutomapHostsSuffixes .exit,.onion

# iptables rules (run as root):
# iptables -t nat -A OUTPUT -m owner --uid-owner tor -j RETURN
# iptables -t nat -A OUTPUT -p udp --dport 53 -j REDIRECT --to-ports 5353
# iptables -t nat -A OUTPUT -p tcp --syn -j REDIRECT --to-ports 9040
# iptables -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
# iptables -A OUTPUT -m owner --uid-owner tor -j ACCEPT
# iptables -A OUTPUT -j DROP
"""


def hash_control_password(password: str) -> str:
    """
    Returns a hashed Tor ControlPort password.
    Uses tor --hash-password if available, otherwise placeholder.
    """
    import subprocess
    try:
        result = subprocess.check_output(
            ["tor", "--hash-password", password], stderr=subprocess.DEVNULL
        ).decode().strip()
        for line in result.splitlines():
            if line.startswith("16:"):
                return line
        return result
    except (FileNotFoundError, subprocess.CalledProcessError):
        return "16:REPLACE_WITH_TOR_HASH_PASSWORD_OUTPUT"


# ─────────────────────────── connectivity ───────────────────────────

def test_tor_connectivity(socks_host: str = "127.0.0.1", socks_port: int = TOR_SOCKS_PORT) -> dict:
    """Test whether Tor SOCKS proxy is reachable and returns Tor IP."""
    result = {"socks_reachable": False, "is_tor": False, "ip": None, "error": None}

    # Test SOCKS port
    try:
        sock = socket.create_connection((socks_host, socks_port), timeout=5)
        sock.close()
        result["socks_reachable"] = True
    except Exception as e:
        result["error"] = str(e)
        return result

    # Test Tor exit IP via check.torproject.org
    try:
        proxy_handler = urllib.request.ProxyHandler({
            "http": f"socks5h://{socks_host}:{socks_port}",
            "https": f"socks5h://{socks_host}:{socks_port}",
        })
        opener = urllib.request.build_opener(proxy_handler)
        import json
        with opener.open(TOR_TEST_URL, timeout=15) as resp:
            data = json.loads(resp.read())
            result["ip"] = data.get("IP")
            result["is_tor"] = data.get("IsTor", False)
    except Exception as e:
        result["error"] = f"Connectivity test failed: {e}"

    return result


def send_control_command(command: str, password: str,
                          host: str = "127.0.0.1", port: int = TOR_CONTROL_PORT) -> str:
    """Send a command to the Tor control port."""
    with socket.create_connection((host, port), timeout=5) as sock:
        def recv():
            data = b""
            while True:
                chunk = sock.recv(4096)
                data += chunk
                if data.endswith(b"\r\n") or b"250 " in data:
                    break
            return data.decode(errors="replace")

        recv()  # banner
        sock.sendall(f'AUTHENTICATE "{password}"\r\n'.encode())
        resp = recv()
        if "250" not in resp:
            raise RuntimeError(f"Authentication failed: {resp}")
        sock.sendall(f"{command}\r\n".encode())
        return recv()


def new_circuit(password: str = "", host: str = "127.0.0.1", port: int = TOR_CONTROL_PORT) -> bool:
    """Request a new Tor circuit (new IP)."""
    try:
        resp = send_control_command("SIGNAL NEWNYM", password=password, host=host, port=port)
        return "250" in resp
    except Exception as e:
        print(f"[!] Circuit renewal failed: {e}")
        return False


# ─────────────────────────── CLI commands ───────────────────────────

def cmd_generate(args):
    out = Path(args.output)
    pw_hash = hash_control_password(args.control_password)
    torrc = TORRC_TEMPLATE.format(
        socks_port=args.socks_port,
        control_port=args.control_port,
        hashed_pw=pw_hash,
    )
    if args.transparent:
        torrc += "\n" + TORRC_TRANSPARENT

    out.write_text(torrc)
    print(f"[+] torrc written to {out}")
    print(f"    SocksPort    : {args.socks_port}")
    print(f"    ControlPort  : {args.control_port}")
    print(f"    HashedPW     : {pw_hash}")
    if args.transparent:
        print("    Transparent proxy config included.")
    print("\nInstall Tor:  sudo apt install tor")
    print(f"Start Tor:    sudo tor -f {out.absolute()}")


def cmd_test(args):
    print(f"[*] Testing Tor SOCKS proxy at {args.host}:{args.port} …")
    result = test_tor_connectivity(args.host, args.port)
    if result["socks_reachable"]:
        print(f"[+] SOCKS port reachable")
        if result["is_tor"]:
            print(f"[+] Connected via Tor! Exit IP: {result['ip']}")
        elif result["ip"]:
            print(f"[?] IP returned: {result['ip']} (NOT flagged as Tor)")
        elif result["error"]:
            print(f"[!] {result['error']}")
    else:
        print(f"[✗] SOCKS port NOT reachable: {result.get('error')}")
        print("    Is Tor running? Try: sudo systemctl start tor")


def cmd_newcircuit(args):
    print("[*] Requesting new Tor circuit …")
    ok = new_circuit(password=args.password, host=args.host, port=args.port)
    if ok:
        print("[+] New circuit established — IP will change shortly.")
        print("    Wait ~10 s then re-test with: python tor_setup.py test")
    else:
        print("[✗] Failed. Is ControlPort enabled and password correct?")


def cmd_bridges(args):
    """Print bridge/obfuscation setup instructions."""
    print("""
Bridge Setup for Censored Networks
===================================
1. Get bridges: https://bridges.torproject.org/
   Or email: bridges@torproject.org  (subject: get transport obfs4)

2. Install obfs4proxy:
   sudo apt install obfs4proxy

3. Add to torrc:
   UseBridges 1
   ClientTransportPlugin obfs4 exec /usr/bin/obfs4proxy
   Bridge obfs4 <IP>:<PORT> <FINGERPRINT> cert=<CERT> iat-mode=0

4. For Snowflake (browser-based bridge):
   ClientTransportPlugin snowflake exec /usr/bin/snowflake-client

5. Restart Tor:
   sudo systemctl restart tor
""")


def main():
    parser = argparse.ArgumentParser(
        description="OPSEC Tor Integration Helper",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    sub = parser.add_subparsers(dest="command")

    # generate
    g = sub.add_parser("generate", help="Generate torrc configuration file")
    g.add_argument("--output", default="torrc", help="Output file path")
    g.add_argument("--socks-port", type=int, default=9050)
    g.add_argument("--control-port", type=int, default=9051)
    g.add_argument("--control-password", default="changeme123")
    g.add_argument("--transparent", action="store_true", help="Add transparent proxy config")

    # test
    t = sub.add_parser("test", help="Test Tor SOCKS connectivity")
    t.add_argument("--host", default="127.0.0.1")
    t.add_argument("--port", type=int, default=9050)

    # newcircuit
    nc = sub.add_parser("newcircuit", help="Request new Tor circuit")
    nc.add_argument("--host", default="127.0.0.1")
    nc.add_argument("--port", type=int, default=9051)
    nc.add_argument("--password", default="")

    # bridges
    sub.add_parser("bridges", help="Print bridge/obfuscation setup guide")

    args = parser.parse_args()
    dispatch = {
        "generate": cmd_generate,
        "test": cmd_test,
        "newcircuit": cmd_newcircuit,
        "bridges": cmd_bridges,
    }
    if args.command in dispatch:
        dispatch[args.command](args)
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
